version: "3.8"

services:
  app:
    build:
      args:
        user: murad
        uid: 1000
      context: .
      dockerfile: docker/app.dockerfile
    image: murad-app
    container_name: murad-app
    environment:
      ENVIRONMENT: development
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - .:/var/www/html:delegated
    networks:
      - murad-net

  nginx:
    image: nginx:1.8-alpine
    container_name: murad-nginx
    restart: unless-stopped
    ports:
      - '${WEB_SERVER_PORT:-8080}:80'
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - murad-net

  db:
    image: 'mysql:5.7'
    container_name: murad-db
    restart: unless-stopped
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'murad-mysql:/var/lib/mysql'
      - .:/var/www/html
    networks:
      - murad-net

networks:
  murad-net:
    driver: bridge

volumes:
  murad-mysql:
    driver: local
